//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyAccountCore.Core.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class npf_history
    {
        [Key]
        public int Id { get; set; }
        public string fundcode { get; set; }
        public string acctcode { get; set; }
        public string docno { get; set; }
        public string batchNo { get; set; }
        public string refno { get; set; }
        public Nullable<System.DateTime> docdate { get; set; }
        public string period { get; set; }
        public string doctype { get; set; }
        public decimal dbamt { get; set; }
        public decimal cramt { get; set; }
        public Nullable<decimal> netamt { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string createdby { get; set; }
    }
}
