//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyAccountCore.Core.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class npf_fundType
    {
        [Key]
        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<DateTime> startDate { get; set; }
        public int processingYear { get; set; }
        public int processingMonth { get; set; }
        public string interestacct { get; set; }
        public string incomeacct { get; set; }
        public string fundacct { get; set; }
        public int receiptno { get; set; }
        public int paymentno { get; set; }
        public int jvno { get; set; }
        public string trusteeacct { get; set; }
        public string profitacct { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
    }
}
