//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyAccountCore.Core.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Beneficiaries = new HashSet<Beneficiary>();
        }
    
        [Key]
        public int PersonID { get; set; }
        public string SVC_NO { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Initials { get; set; }
        public string Title { get; set; }
        public string Sex { get; set; }
        public string email { get; set; }
        public string homeaddress { get; set; }
        public Nullable<System.DateTime> dateemployed { get; set; }
        public Nullable<int> bank { get; set; }
        public string accountno { get; set; }
        public string bankbranch { get; set; }
        public string Factory { get; set; }
        public Nullable<int> Payrollclass { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> ExitTypeid { get; set; }
        public Nullable<System.DateTime> dateleft { get; set; }
        public Nullable<int> branchid { get; set; }
        public Nullable<int> staffbranchid { get; set; }
        public Nullable<int> Departmentid { get; set; }
        public string MaidenName { get; set; }
        public string Command { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string PhotoPath { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> LiveStatus { get; set; }
        public Nullable<int> IdentificationId { get; set; }
        public Nullable<int> countryid { get; set; }
        public Nullable<int> LocalGovernmentareaId { get; set; }
        public Nullable<int> geozoneid { get; set; }
        public byte[] FingerPrint { get; set; }
        public string IdentityType { get; set; }
        public string IdentifyNumber { get; set; }
        public Nullable<System.DateTime> IdentityExpiryDate { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public string GSMNumber { get; set; }
        public Nullable<int> tribeId { get; set; }
        public string Birthplace { get; set; }
        public Nullable<int> religiondenominationid { get; set; }
        public Nullable<int> BloodGroupid { get; set; }
        public Nullable<int> entrymodeid { get; set; }
        public Nullable<int> commissiontypeid { get; set; }
        public Nullable<int> commissionid { get; set; }
        public Nullable<System.DateTime> commissiondate { get; set; }
        public Nullable<System.DateTime> senioritydate { get; set; }
        public string ExitReason { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> SpecialisationAreaId { get; set; }
        public string hubbies { get; set; }
        public string NOKFileName { get; set; }
        public Nullable<int> SortId { get; set; }
        public int rank { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiary> Beneficiaries { get; set; }
        public virtual Rank Rank1 { get; set; }
    }

}
