//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyAccountCore.Core.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Pf_LoanRegister
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> LoanTypeID { get; set; }
        public Nullable<int> FundTypeID { get; set; }
        public DateTime ApproveDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Tenure { get; set; }
        public string BankID { get; set; }
        public string ChequeNo { get; set; }
        public DateTime EffectiveDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string VoucherNo { get; set; }
        public string remarks { get; set; }
        public string StatusAndStatusDate { get; set; }
        public string LoanAppNo { get; set; }
        public string batchNo { get; set; }
        public int loancount { get; set; }
        public string LoanStatus { get; set; }
        public string loanAccount { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string createdby { get; set; }
    }
}
