//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyAccountCore.Core.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class py_bank
    {
        [Key]
        public int Id { get; set; }
        public string bankcode { get; set; }
        public string branchcode { get; set; }
        public string bankname { get; set; }
        public string branchname { get; set; }
        public string address { get; set; }
        public string CompanyAcctNo { get; set; }
        public string ContactMgrAccountant { get; set; }
        public string remarks { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string cbn_code { get; set; }
        public string cbn_branch { get; set; }
    }
}
